version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "11:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "11:00"
